require File.expand_path("#{File.dirname(__FILE__)}/../require")
Require.spec_rakefile!

begin
  ActiveWrapper::Tasks.setup(
    :base => File.dirname(__FILE__),
    :env => 'test'
  )
rescue Exception
end