require File.expand_path(File.dirname(__FILE__) + '/../lib/also_migrate/gems')

AlsoMigrate::Gems.require(:spec_rake)

require 'active_wrapper/tasks'

#begin
  ActiveWrapper::Tasks.new(
    :base => File.dirname(__FILE__),
    :env => 'test'
  )
# rescue Exception
# end